# Generated by Django 4.2.2 on 2023-06-28 13:27

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='DaHocHetLop5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DangKyHoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Phuong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Truong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('avatar', models.ImageField(null=True, upload_to='users/%Y/%m/')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='TruongVaQuan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LeQuyDonWebApp.quan')),
                ('truong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LeQuyDonWebApp.truong')),
            ],
        ),
        migrations.CreateModel(
            name='QuanvaPhuong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phuong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LeQuyDonWebApp.phuong')),
                ('quan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LeQuyDonWebApp.quan')),
            ],
        ),
        migrations.CreateModel(
            name='DonTuyenSinh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=100)),
                ('sdt', models.CharField(max_length=100)),
                ('hokhau', models.CharField(max_length=100)),
                ('choDK', models.CharField(max_length=100)),
                ('cccd', models.IntegerField()),
                ('is_parent', models.CharField(max_length=100)),
                ('truongtieuhoc', models.CharField(max_length=100)),
                ('tenhs', models.CharField(max_length=100)),
                ('ngaysinh', models.DateField(auto_now=True)),
                ('gioitinh', models.CharField(max_length=100)),
                ('dantoc', models.CharField(max_length=100)),
                ('tongiao', models.CharField(max_length=100)),
                ('noisinh', models.CharField(max_length=100)),
                ('madinhdanh', models.CharField(max_length=100)),
                ('diachi', models.CharField(max_length=100)),
                ('phuong', models.CharField(max_length=100)),
                ('diachithuongtru', models.CharField(max_length=100)),
                ('quanthuongtru', models.CharField(max_length=100)),
                ('phuongthuongtru', models.CharField(max_length=100)),
                ('dienchinhsach', models.CharField(max_length=100, null=True)),
                ('suckhoe', models.CharField(max_length=100)),
                ('tiengviet5', models.FloatField(max_length=100)),
                ('toan5', models.FloatField(max_length=100)),
                ('tongdiem', models.FloatField()),
                ('chungchita', models.CharField(max_length=100)),
                ('cambridge', models.IntegerField(null=True)),
                ('toefl', models.IntegerField(null=True)),
                ('pearson', models.FloatField(null=True)),
                ('hocba', models.CharField(max_length=100)),
                ('boi', models.CharField(max_length=100)),
                ('nangkhieu', models.CharField(max_length=100, null=True)),
                ('tdtt', models.CharField(max_length=100, null=True)),
                ('tntp', models.CharField(max_length=100, null=True)),
                ('tencha', models.CharField(max_length=100)),
                ('namsinhcha', models.IntegerField()),
                ('nghenghiep', models.CharField(max_length=100)),
                ('chucvu', models.CharField(max_length=100)),
                ('noicongtac', models.CharField(max_length=100)),
                ('sdtcha', models.IntegerField()),
                ('tenme', models.CharField(max_length=100)),
                ('namsinhme', models.IntegerField()),
                ('nghenghiepme', models.CharField(max_length=100)),
                ('chucvume', models.CharField(max_length=100)),
                ('noicongtacme', models.CharField(max_length=100)),
                ('sdtme', models.CharField(max_length=100)),
                ('chonlop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LeQuyDonWebApp.dangkyhoc')),
                ('quan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LeQuyDonWebApp.quan')),
                ('trinhdo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LeQuyDonWebApp.dahochetlop5')),
            ],
        ),
    ]
